spring:
  application:
    name: bi-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bi
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lzf.bibackend

# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn

openai:
  api:
    key: "70084fb3-e002-4301-8d37-6b5cf2750bc9"
    endpoint-id: "ep-20240801211603-5f56h"
#    url: "https://api.pumpkinaigc.online/v1/chat/completions"
#    key: "sk-R6UYHcAEzcPIunSG5bAdEa64Bb21467cA8F506D30b0e10Df"

thread-pool:
  core-pool-size: 2
  maximum-pool-size: 4
  keep-alive-time: 100
  work-queue-capacity: 100

